import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Eterno Pet — tokens backed by CSS vars for dark mode support
        surface:                    'rgb(var(--color-surface) / <alpha-value>)',
        'surface-dim':              'rgb(var(--color-surface-dim) / <alpha-value>)',
        'surface-bright':           'rgb(var(--color-surface-bright) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--color-surface-container-lowest) / <alpha-value>)',
        'surface-container-low':    'rgb(var(--color-surface-container-low) / <alpha-value>)',
        'surface-container':        'rgb(var(--color-surface-container) / <alpha-value>)',
        'surface-container-high':   'rgb(var(--color-surface-container-high) / <alpha-value>)',
        'surface-container-highest':'rgb(var(--color-surface-container-highest) / <alpha-value>)',
        'surface-variant':          'rgb(var(--color-surface-variant) / <alpha-value>)',
        'on-surface':               'rgb(var(--color-on-surface) / <alpha-value>)',
        'on-surface-variant':       'rgb(var(--color-on-surface-variant) / <alpha-value>)',
        background:                 'rgb(var(--color-background) / <alpha-value>)',
        'on-background':            'rgb(var(--color-on-background) / <alpha-value>)',
        primary:                    'rgb(var(--color-primary) / <alpha-value>)',
        'on-primary':               'rgb(var(--color-on-primary) / <alpha-value>)',
        'primary-container':        'rgb(var(--color-primary-container) / <alpha-value>)',
        'on-primary-container':     'rgb(var(--color-on-primary-container) / <alpha-value>)',
        'primary-fixed':            'rgb(var(--color-primary-fixed) / <alpha-value>)',
        'primary-fixed-dim':        'rgb(var(--color-primary-fixed-dim) / <alpha-value>)',
        'on-primary-fixed':         'rgb(var(--color-on-primary-fixed) / <alpha-value>)',
        'on-primary-fixed-variant': 'rgb(var(--color-on-primary-fixed-variant) / <alpha-value>)',
        'inverse-primary':          'rgb(var(--color-inverse-primary) / <alpha-value>)',
        secondary:                  'rgb(var(--color-secondary) / <alpha-value>)',
        'on-secondary':             'rgb(var(--color-on-secondary) / <alpha-value>)',
        'secondary-container':      'rgb(var(--color-secondary-container) / <alpha-value>)',
        'on-secondary-container':   'rgb(var(--color-on-secondary-container) / <alpha-value>)',
        'secondary-fixed':          'rgb(var(--color-secondary-fixed) / <alpha-value>)',
        tertiary:                   'rgb(var(--color-tertiary) / <alpha-value>)',
        'on-tertiary':              'rgb(var(--color-on-tertiary) / <alpha-value>)',
        'tertiary-container':       'rgb(var(--color-tertiary-container) / <alpha-value>)',
        'tertiary-fixed':           'rgb(var(--color-tertiary-fixed) / <alpha-value>)',
        'tertiary-fixed-dim':       'rgb(var(--color-tertiary-fixed-dim) / <alpha-value>)',
        'on-tertiary-fixed':        'rgb(var(--color-on-tertiary-fixed) / <alpha-value>)',
        'on-tertiary-fixed-variant':'rgb(var(--color-on-tertiary-fixed-variant) / <alpha-value>)',
        outline:                    'rgb(var(--color-outline) / <alpha-value>)',
        'outline-variant':          'rgb(var(--color-outline-variant) / <alpha-value>)',
        'inverse-surface':          'rgb(var(--color-inverse-surface) / <alpha-value>)',
        'inverse-on-surface':       'rgb(var(--color-inverse-on-surface) / <alpha-value>)',
        error:                      'rgb(var(--color-error) / <alpha-value>)',
        'on-error':                 'rgb(var(--color-on-error) / <alpha-value>)',
        'error-container':          'rgb(var(--color-error-container) / <alpha-value>)',
        'on-error-container':       'rgb(var(--color-on-error-container) / <alpha-value>)',
        // shadcn compat
        border:       'hsl(var(--border))',
        input:        'hsl(var(--input))',
        ring:         'hsl(var(--ring))',
        card:         { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        popover:      { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        muted:        { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent:       { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        destructive:  { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
      },
      fontFamily: {
        serif: ['Noto Serif', 'Georgia', 'serif'],
        sans:  ['Manrope', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm:      '0.25rem',
        lg:      '1rem',
        xl:      '1.5rem',
        '2xl':   '2rem',
        '3xl':   '2.5rem',
        '4xl':   '3rem',
        full:    '9999px',
      },
      maxWidth: {
        container: '1200px',
      },
      boxShadow: {
        soft:      '0 4px 24px -4px rgba(74, 93, 78, 0.06)',
        card:      '0 4px 20px -5px rgba(141,170,145,0.08)',
        memorial:  '0 32px 64px -16px rgba(74,93,78,0.08)',
        premium:   '0 40px 80px -20px rgba(74,93,78,0.3)',
      },
      animation: {
        'fade-in':  'fade-in 0.4s ease-out',
        'slide-up': 'slide-up 0.4s ease-out',
      },
      keyframes: {
        'fade-in':  { from: { opacity: '0' }, to: { opacity: '1' } },
        'slide-up': { from: { opacity: '0', transform: 'translateY(12px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
      },
    },
  },
  plugins: [],
};

export default config;
